### ISSUE TITLE
Allow selected images to be manually ordered

### ISSUE THREAD

**Issue by pierrese** [xwp/wp-customize-image-gallery-control#5]
Hello,

I would like to know if there is a way of reordering the pictures (I want a gallery ordered manually) with this plugin, or a simple way of adapt it to do that.

Thank you very much for your help,

**Comment by westonruter** [comment]
@pierrese Hi, I don't think that is supported yet, no. According to https://make.xwp.co/2016/08/12/image-gallery-control-for-the-customizer/#comment-1656

> The plugin is now updated to display images in a consistent order. The images in the control will be displayed in the same order as in media library.

It seems that the Media Library integration doesn't have the additional gallery view for allowing the selected images to be re-ordered.

@miina Is this a requirement that has come up before?

**Comment by pierrese** [comment]
I understand.
This feature is, for example, in the woocommerce plugin in the gallery custom box that you can find in the product page.
The problem is that I don't know how to adapt this code (php and jquery) to do the same in this plugin.

Thank you,

**Comment by miina** [comment]
@westonruter This requirement hasn't come up before. However, just created a PR ( #6 ) that should allow ordering the images manually by dragging/dropping within the Customizer field, and removes the forced order of Media Library.

@pierrese Hopefully this is helpful.

**Comment by pierrese** [comment]
Thank you very much !
It works very well and will allow me to use the plugin. Thank you for your help.

**Comment by westonruter** [comment]
👏
